### ISSUE TITLE
Issue when certain values are supplied to `qs` with lognormal tails

### ISSUE THREAD

**Issue by lshandross** [reichlab/distfromq#19]
When `tail_dist="lnorm"`, it seems like the `qs` argument is having issues if the provided vector has several groups of repeated values with multiple zeros at the beginning. This is the error message that is printed when an error is thrown:

> Error in if (ab_sq > 9) { : missing value where TRUE/FALSE needed

This is the code that throws the above error when I run it:

```
distfromq::make_q_fn(
        ps = seq(0.05, 0.95, 0.1),
        qs = c(rep(0, 4), rep(1, 3), rep(5, 3)),
        dup_tol = 1e-06,
        zero_tol = 1e-12,
        tail_dist = "lnorm")(seq(from = 0, to = 1, length.out = 1e4 + 2)[2:1e4]) 
```
Other combinations of exactly three unique values with a series of zeros at the beginning also cause the same issue, but the following vectors supplied to `qs` DO NOT:

```
# seq(0:9) 
# sort(rep(0:4, 2)) 
# c(rep(0, 4), rep(1, 2), 2, 2, 3, 3) 
# c(rep(0, 8), rep(1, 1), 2) 
# c(rep(0, 1), rep(1, 8), 2) 
# c(rep(0, 1), rep(1, 7), 2, 3) 
# c(rep(1, 4), rep(3, 3), 5, 5, 5) 
```

The error message persists regardless of the value supplied to `length.out` but goes away if `dup_tol` is increased to 1 or greater.

**Comment by elray1** [comment]
closed via #20
