### ISSUE TITLE
add some clarity to the documentation for the spline_cdf*() functions and their unified documentation

### ISSUE THREAD

**Issue by nickreich** [reichlab/distfromq#30]
I merged all of the documentation for three `spline_cdf*()` functions into one Roxygen file in #29, but the file doesn't disambiguate the uses of each function.

**Comment by elray1** [comment]
I think we should only be exporting and publicly documenting... well, maybe not any of these, but at most `spline_cdf`.  More generally, it seems like documentation is showing up for functions that don't have an `@export` tag.  Maybe that's not ideal?

**Comment by elray1** [comment]
Maybe not totally clear from my comment just above, but `spline_cdf_grid_interp` and `spline_cdf_direct` are intended to be internal-only functions that I would not expect a user to call.

**Comment by nickreich** [comment]
Aha. I was confused because documentation was inconsistent for unexported functions. Maybe to have no documentation show up we'd need to add `@noRd` tags to the function definitions for internal functions that have documentation?
