### ISSUE TITLE
Ensure consistency between cumulative distribution functions and quantile functions

### ISSUE THREAD

**Issue by elray1** [reichlab/distfromq#6]
We should provide functionality to handle two cases, depending on whether the primary object that was elicited was the quantile function or the cumulative distribution function:

1. The quantile function (qf) is elicited; distinct `ps` are provided and the modeler is asked to provide the corresponding `qs`, which may contain duplicated values if the distribution has a point mass. In this case, on the interior we should fit a model for `qs ~ ps`, i.e., directly estimate the quantile function. Then to obtain an estimate of the cdf, we invert the estimate of the qf in two steps:
    1. if the value `x` at which we want to evaluate the cdf is equal to a duplicated value in `qs`, choose the largest of the corresponding `ps`
    2. else, the monotonic spline for the qf is directly invertible at `x`; use that. 
2. The cdf is elicited; distinct `qs` are provided and the modeler is asked to provide the corresponding `ps`, which may contain duplicated values if the distribution has a region with zero probability. In this case, on the interior we should fit a model for `ps ~ qs`, i.e., directly estimate the cdf. Then to obtain an estimate of the qf, we invert the estimated cdf using similar ideas to the above:
    1. if the value `p` at which we want to evaluate the qf is equal to a duplicated value in `ps`, choose the smallest of the corresponding `qs`.
    2. else, the monotonic spline for the cdf is directly invertible at `p`; use that

Here's a high level list of things we need to do in order to implement this:
1. Decide on an approach to monotonic spline modeling that we want to use
2. Implement a function that inverts a monotonic spline fit
3. Add an argument to all of the `make_*_fun` functions specifying whether the cdf or qf was elicited, so that we can branch appropriately

**Comment by aaronger** [comment]
I guess I'm not sure what you mean by "fit model, i.e., directly estimate".  My thinking was that if a forecaster provides a single q (or p) for (necessarily consecutive) ps (or qs), we should return a discontinuous cdf (or qf) with "inverse" constant between the endpoints of intervals containing multiple provided function values for a single input.

**Comment by elray1** [comment]
Here are some points:

- I could be convinced to do something else.
- In general, even when all `ps` and `qs` are distinct, a function estimated via `stats::splinefun(qs, ps)` (which "directly estimates" the cdf) will not be the inverse of a function estimated via `stats::splinefun(ps, qs)` (which "directly estimates" the qf). That means that if we want our estimates of the cdf and the qf to be inverses, we have to make a decision about which of those functions to estimate "directly" and then obtain the other "indirectly" by inverting the first.
- I agree that whichever decision is made regarding which of the cdf/qf is estimated directly or obtained by inverting the other, if there are duplicated values in `ps` or `qs`, there will be constant regions/discontinuities in one or the other of the cdf or qf. (If there are duplicated values in both `ps` and `qs`, both the qf and the cdf would have both constant regions and discontinuities.)
- My suggestion was to add an argument to allow the user to specify which function is estimated directly, with the idea that it will typically make sense for this to correspond to the function that was elicited because then you can guarantee that one or the other of `ps` or `qs` would not contain any duplicate values -- so we should be able to set it up so that the spline fit only has to deal with constant regions (which it handles well), but not with discontinuities (which it does not handle well). Then, discontinuities in the cdf or qf would be addressed during the inversion process rather than the spline/curve fitting process.
- To illustrate, consider the example from the vignette with repeated quantile values (`qs`) at multiple probability levels (`ps`). I'll paste in the relevant plots below showing fits from a spline regressing `ps` on `qs`, i.e., directly estimating the cdf, and from a spline regressing `qs` on `ps`, i.e. directly estimating the qf. In this example, the cdf should have a discontinuity and the qf should have a constant region. This is captured by default in the qf fit, but not in the cdf fit. In this case, I was thinking that the easiest route forward would be to work with the well-behaved qf fit and invert it to obtain the cdf. Working with the cdf as the primary object to estimate would require some manual intervention near the discontinuity.
![image](https://user-images.githubusercontent.com/5132208/210098282-33a912e6-f419-49fc-97af-9a51cab9825b.png)
![image](https://user-images.githubusercontent.com/5132208/210098329-5a65c37e-8190-4e3f-9b7a-1be51c08ca62.png)
- But on further reflection, there are disadvantages to this approach:
    - differentiating a cdf that's obtained by inverting a qf might be more work?
    - this suggestion doesn't handle a situation where there are duplicated `ps` and duplicated `qs` (though I doubt this situation would come up much in practice)

**Comment by aaronger** [comment]
A few quick thoughts.
For my applications, I'm really not too concerned with differentiability or even continuity.  I feel like iterative allocation procedures should and probably can pretty easily be made robust to point masses.  And if they can't, I think it should be the caller that deals with the problem, not the distribution factory.  
I am more concerned with being able to articulate some general inferential principle by which the inter/extrapolations are being made. I don't know what this will be yet - my hope is that we could do something with maxent ideas - but my bet is that whatever we end up with, it will either require or at least be most consistent with repeated forecaster inputs indicating a discontinuity for whichever function is being elicited. Therefore I would think the best spline fitting target would be whichever discrete function is defined (i.e., is not multivalued), with the other being it's discontinuous "inverse".
If we are in the situation of having repetitions in both the ps and qs, then I don't know for sure but I think this would be a good time to tell the user that they need to make some choices and/or fix their data so that at least one column has no repetions.

**Comment by elray1** [comment]
Here's a proposal for an API (function signatures for `make_p_fn` and `make_q_fn` similar):

```
#' Creates a function that evaluates the probability density function of an
#' approximation to a distribution obtained by interpolating and extrapolating
#' from a set of quantiles of the distribution.
#'
#' @param ps vector of probability levels
#' @param qs vector of quantile values correponding to ps
#' @param interior_method method for interpolating the distribution on the
#'    interior of the provided `qs`. Options provided by this package include
#'    `"spline_cdf"` and `"spline_qf"`. The user may also provide a custom function;
#'    see details for more.
#' @param interior_args an optional named list of arguments that are passed
#'    on to the `interior_method`
#' @param lower_tail_dist name of parametric distribution for the lower tail
#' @param upper_tail_dist name of parametric distribution for the upper tail
#' 
#' @details The default `interior_method`, `"spline_cdf"`, represents the distribution
#'    as a sum of a discrete component at any points where there are duplicated
#'    `qs` for multiple different `ps` and a continuous component that is estimated
#'    by using a monotonic cubic spline that interpolates the provided `(q, p)` pairs
#'    as an estimate of the cdf. The density function is then obtained by differentiating
#'    this estimate of the cdf.
#' 
#'    Optionally, the user may provide another function that accepts arguments
#'    `ps`, `qs`, `fn_type` (which will be either `"d"`, `"p"`, or `"q"`), and additional named
#'    arguments to be specified via `interior_args`. This function should return a function
#'    with arguments `x`, `log` that evaluates the pdf or its logarithm.
#'
#' @return a function with arguments `x` and `log` that can be used to evaluate
#'   the approximate density function (or its `log`) at the points `x`.
#' @export
make_d_fn <- function(ps, qs, interior_method = c("spline_cdf", "spline_qf"),
                      interior_args = list(),
                      lower_tail_dist = "norm", upper_tail_dist = "norm")```
```

Then `spline_cdf` (and `spline_qf`) are functions that fit a monotonic spline to the "continuous part" of the distribution (or quantile) function, and then: (a) invert to obtain the quantile (or distribution) function, and (b) differentiate the cdf to get to a density function.

**Comment by aaronger** [comment]
This sounds good. Just to make sure I understand, when the user provides another `interior_method` the function is just filling in or replacing the exterior values, right?

**Comment by elray1** [comment]
The idea is that `interior_method` is going to handle estimation of the distribution on the interior of the provided quantiles, and it's a "function factory" that returns a function that evaluates either the pdf, cdf, or qf depending on the value of `fn_type`. Handling of the tails is still done via a location-scale parametric family as before.

**Comment by aaronger** [comment]
OK got it - this seems like a good design strategy.
