### ISSUE TITLE
What is this saying?

### ISSUE THREAD

**Issue by aaronger** [reichlab/distfromq#7]
> Because the spline passes through the points $(q_1, \tau_1)$ and $(q_K, \tau_K)$, the integral of its derivative over the interval $[q_1, q_K]$ is equal to $\tau_K - \tau_1$.

This reads to me as a tautology, but I feel like I'm missing some subtlety.

**Comment by elray1** [comment]
You're not missing anything in terms of this statement :) My goal was to explain that indeed we're going to end up with a valid CDF after going through all of this.  But maybe I didn't end up explaining that very clearly.

**Comment by aaronger** [comment]
I guess I see any monotonic function interpolating the data as a valid cdf - so this feels a little like saying because we construct the function to pass through these points, it passes through these points.
